import esbuild from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

await mkdir("dist", { recursive: true });
await writeFile("dist/.hotreload", "");

const mainBuildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  minify: prod,
} satisfies esbuild.BuildOptions;

const staticBuildOptions = {
  entryPoints: [
    { in: "styles.css", out: "styles" },
    { in: "manifest.json", out: "manifest" },
  ],
  loader: {
    ".css": "copy",
    ".json": "copy",
  },
  logLevel: "info",
  outdir: "dist",
} satisfies esbuild.BuildOptions;

if (prod) {
  await Promise.all([esbuild.build(mainBuildOptions), esbuild.build(staticBuildOptions)]);
} else {
  const [mainContext, staticContext] = await Promise.all([
    esbuild.context(mainBuildOptions),
    esbuild.context(staticBuildOptions),
  ]);

  await Promise.all([mainContext.watch(), staticContext.watch()]);
}
